config/routes.rb
Myflix::Application.routes.draw do
  root to:'pages#front'
  get 'home', to: 'videos#index'
  resources :videos, only: [:index, :show] do 
    collection do 
      post :search, to: 'videos#search'
    end 
    resources :reviews, only: [:create]
  end 

  namespace :admin do 
    resources :videos, only: [:new, :create]
  end 

  get "people", to: "relationships#index"
  resources :relationships, only: [:create, :destroy]

  resources :categories, only: [:index, :show]
  resources :queue_items, only: [:create, :destroy]

  post 'update_queue', to: 'queue_items#update_queue'
  get 'my_queue',   to: 'queue_items#index'

  get 'ui(/:action)', controller: 'ui'
  get 'register',  to: 'users#new'
  get 'register/:token', to: "users#new_with_invitation_token", as: "register_with_token"
  get 'sign_in',   to: 'sessions#new'
  get 'sign_out',  to: 'sessions#destroy'
  resources :users, only: [:create, :show]
  resources :sessions, only: [:create]

  get "forgot_password", to: "forgot_passwords#new"
  resources :forgot_passwords, only: [:create]
  get "forgot_password_confirmation", to: "forgot_passwords#confirm"
  resources :password_resets, only: [:show, :create]
  get "expired_token" , to: "pages#expired_token"

  resources :invitations, only: [:new, :create]

end
  

app/controllers/forgot_passwords_controller.rb
class ForgotPasswordsController < ApplicationController 

  def create
    user = User.where(email: params[:email]).first
    if user 
      Usermailer.send_forgot_password(user).deliver
      redirect_to forgot_password_confirmation_path
    else 
      flash[:danger] = params[:email].blank? ? "Email cannot be blank." : "No user with that email found in our system."
      redirect_to forgot_password_path
    end 
  end
end 

app/views/forgot_passwords/confirm.html.haml
%section.confirm_password_reset.container
  .row
    .col-sm-10.col-sm-offset-1
      %p We have send an email with instruction to reset your password.

app/views/forgot_passwords/new.html.haml
%section.forgot_password.container
  .row
    .col-sm-10.col-bg-offset-1
      = form_tag forgot_passwords_path, class: "sign_in" do 
        %header
          %h1 Forgot Password?
          %p We will send you an email with a link that you can use to reset your password.
        .form-group
          = label_tag :email, "Email Address"
          .row
            .col-sm-4
          = text_field_tag :email, nil, class: "form-control"
        .form-group.action
          %input(type="submit" value="Send Email" class="btn btn-default")