config/routes.rb
Myflix::Application.routes.draw do
  root to:'pages#front'
  get 'home', to: 'videos#index'
  resources :videos, only: [:index, :show] do 
    collection do 
      post :search, to: 'videos#search'
    end 
    resources :reviews, only: [:create]
  end 

  namespace :admin do 
    resources :videos, only: [:new, :create]
  end 

  get "people", to: "relationships#index"
  resources :relationships, only: [:create, :destroy]

  resources :categories, only: [:index, :show]
  resources :queue_items, only: [:create, :destroy]

  post 'update_queue', to: 'queue_items#update_queue'
  get 'my_queue',   to: 'queue_items#index'

  get 'ui(/:action)', controller: 'ui'
  get 'register',  to: 'users#new'
  get 'register/:token', to: "users#new_with_invitation_token", as: "register_with_token"
  get 'sign_in',   to: 'sessions#new'
  get 'sign_out',  to: 'sessions#destroy'
  resources :users, only: [:create, :show]
  resources :sessions, only: [:create]

  get "forgot_password", to: "forgot_passwords#new"
  resources :forgot_passwords, only: [:create]
  get "forgot_password_confirmation", to: "forgot_passwords#confirm"
  resources :password_resets, only: [:show, :create]
  get "expired_token" , to: "pages#expired_token"

  resources :invitations, only: [:new, :create]

end
  

app/models/user.rb
class User < ActiveRecord::Base 

  has_many :queue_items, -> {order("position")}
  has_many :reviews, -> {order("created_at DESC")}

  has_many :following_relationships, class_name: "Relationship", foreign_key: "follower_id"
  has_many :leading_relationships, class_name: "Relationship", foreign_key: "leader_id"
  validates_presence_of   :email, :password, :full_name
  validates_uniqueness_of :email

  has_secure_password validations: false 

  #before_save :generate_slug!

  include Tokenable
  
  # def to_param
  #   self.slug
  # end

  # def generate_slug!
  #   self.slug = self.full_name.gsub(' ', '-').downcase
  # end

  def admin?
    self.admin == true
  end

  def normalize_queue_item_position 
    queue_items.each_with_index do |queue_item, index|
      queue_item.update_attributes(position: index + 1) 
    end 
  end
  
  def queued_video?(video)
    queue_items.map(&:video).include?(video)
  end

  def follows?(another_user)
    following_relationships.map(&:leader).include?(another_user)
  end

  def follow(another_user)
    following_relationships.create(leader: another_user) if can_follow?(another_user)
  end

  def can_follow?(another_user)
    !(self.follows?(another_user) || self == another_user)
  end
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController 

  before_filter :require_user, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    result = UserSignup.new(@user).sign_up(params[:stripeToken], params[:invitation_token])
    if result.successful? 
      flash[:success] = "Welcome to MyFLix."
      redirect_to sign_in_path
    else 
      flash[:danger] = result.error_message
      render :new
    end 
  end

  def show
    @user = User.find(params[:id])
  end

  def new_with_invitation_token 
    invitation = Invitation.where(token: params[:token]).first
    if invitation
      @user = User.new(email: invitation.recipient_email)
      @invitation_token = invitation.token
      render :new
    else 
      redirect_to expired_token_path 
    end
  end

  private 

  def user_params
    params.require(:user).permit(:email, :password, :full_name, :slug, :token)
  end
end

app/views/users/new.html.haml
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script type="text/javascript">
Stripe.setPublishableKey("#{ENV["STRIPE_PUBLISHABLE_KEY"]}");
</script>

= javascript_include_tag 'payment'

%section.register.container
  .row
    .col-sm-10.col-sm-offset-1
      = bootstrap_form_for @user, html: { class: "form-horizontal", id: "payment-form"} do |f| 
        %header
          %h1 Register
        %fieldset
          = f.text_field :email, label: "Email Address"
          = f.password_field :password
          = f.text_field :full_name, label: "Full Name" 
          = hidden_field_tag :invitation_token, @invitation_token   
        %fieldset.credit_card
          %span.payment-errors
          .form-group
            %label.control-label.col-sm-2(for="credit-card-number") Credit Card Number
            .col-sm-6
              %input.form-control#credit-card-number(type="text" data-stripe="number")
          .form-group
            %label.control-label.col-sm-2(for="security-code") Security Code
            .col-sm-6
              %input.form-control#security-code(type="text" data-stripe="cvc")
          .form-group
            %label.control-label.col-sm-2 Expiration
            .col-sm-3
              = select_month(Date.today, {add_month_numbers: true},  class: 'form-control', data: {stripe: "exp-month"})
            .col-sm-2
              = select_year(Date.today.year, {start_year: Date.today.year, end_year: Date.today.year + 4}, class: 'form-control', data: {stripe: "exp-year"})
        %fieldset.actions.control-group.col-sm-offset-2
          .controls
            %input(type="submit" value="Sign Up" class="btn btn-default")

app/views/users/show.html.haml
%section.user.container
  .row
    .col-sm-10.col-sm-offset-1
      %article
        %header
          %img(src="http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(@user.email.downcase)}?s=40")
          %h2 #{@user.full_name}'s video collections (#{@user.queue_items.count})
          %p 
            = link_to "Follow", relationships_path(leader_id: @user.id), method: :post, class: "btn btn-default" if current_user.can_follow?(@user)
        %table.table
          %thead
            %tr
              %th(width="30%") Video Title
              %th(width="15%") Genre
          %tbody
            - @user.queue_items.each do |queue_item| 
              %tr
                %td
                  = link_to "#{queue_item.video_title}", video_path(queue_item.video)
                %td
                  = link_to "#{queue_item.category_name}", category_path(queue_item.category)

%section.user_reviews.container
  .row
    .col-sm-10.col-sm-offset-1
      %header
        %h3 #{@user.full_name}'s Reviews (#{@user.reviews.count})
      %ul
        - @user.reviews.each do |review| 
          %article.review
            %li.row
              .col-sm-2
                %p
                  = link_to "#{review.video.title}", video_path(review.video)
                %col Rating: #{review.rating} / 5
              .col-sm-8
                %p #{review.content}