config/routes.rb
Myflix::Application.routes.draw do
  root to:'pages#front'
  get 'home', to: 'videos#index'
  resources :videos, only: [:index, :show] do 
    collection do 
      post :search, to: 'videos#search'
    end 
    resources :reviews, only: [:create]
  end 

  namespace :admin do 
    resources :videos, only: [:new, :create]
  end 

  get "people", to: "relationships#index"
  resources :relationships, only: [:create, :destroy]

  resources :categories, only: [:index, :show]
  resources :queue_items, only: [:create, :destroy]

  post 'update_queue', to: 'queue_items#update_queue'
  get 'my_queue',   to: 'queue_items#index'

  get 'ui(/:action)', controller: 'ui'
  get 'register',  to: 'users#new'
  get 'register/:token', to: "users#new_with_invitation_token", as: "register_with_token"
  get 'sign_in',   to: 'sessions#new'
  get 'sign_out',  to: 'sessions#destroy'
  resources :users, only: [:create, :show]
  resources :sessions, only: [:create]

  get "forgot_password", to: "forgot_passwords#new"
  resources :forgot_passwords, only: [:create]
  get "forgot_password_confirmation", to: "forgot_passwords#confirm"
  resources :password_resets, only: [:show, :create]
  get "expired_token" , to: "pages#expired_token"

  resources :invitations, only: [:new, :create]

end
  

app/models/video.rb
 class Video < ActiveRecord::Base 
  belongs_to :category
  has_many :reviews, -> {order("created_at DESC")}

  mount_uploader :large_cover, LargeCoverUploader 
  mount_uploader :small_cover, SmallCoverUploader

  validates_presence_of :title, :description

  #before_save :generate_slug!

  # def to_param
  #   self.slug
  # end

  # def generate_slug!
  #   self.slug = self.title.gsub(' ', '-').downcase
  # end

  def title_only?
    description.blank?
  end

  def self.search_by_title(search_term)
    return [] if search_term.blank?
    where("title LIKE ?",  "%#{search_term}%").order("created_at DESC")
  end

  def average_rating
   reviews.average(:rating).round(1) if reviews.average(:rating)
  end 
end  

app/controllers/admin/videos_controller.rb
 class Admin::VideosController < AdminController 

  before_filter :require_user
  before_filter :require_admin 

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)
     if @video.save
      flash[:success] = "You have successfully added the video: #{@video.title}."
      redirect_to new_admin_video_path
    else 
      flash[:danger] = "Your video was not added. Please correct the errors."
      render :new
    end 
  end

  private

  def video_params
    params.require(:video).permit(:title, :category_id, :description, :small_cover, :large_cover)
  end
end  

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_filter :require_user 

  def index
    @videos = Video.all 
    @categories = Category.all
  end

  def show
    @video = VideoDecorator.decorate(Video.find(params[:id]))
    @reviews = @video.reviews
  end

  def search
    @results = Video.search_by_title(params[:search_term])
  end
end 

app/views/videos/index.html.haml
%article.video_category
  - @categories.each do |category|
    %header
      %h3= category.name
    .videos.row 
      - category.recent_videos.each do |video| 
        .video.col-sm-2
          = link_to video do 
            %img(src="#{video.small_cover}")

app/views/videos/search.html.haml
%article.video_category
  - @results.each do |video| 
    .video.span2
      = link_to video do 
        %img(src="#{video.small_cover_url}")  

app/views/videos/show.html.haml
%article.video
  .container
    .row
      .video_large_cover.col-sm-7.col-sm-offset-1
        %img(src="#{@video.large_cover}")
      .video_info.col-sm-3
        %header
          %h3= @video.title
          %span Rating:  
          = @video.average_rating
        %p= @video.description
        .actions
          %a.btn.btn-primary(href="#{@video.video_url}") Watch Now
          = link_to "+ My Queue", queue_items_path(video_id: @video.id), method: :post, class: 'btn btn-default' unless current_user.queued_video?(@video)
%section.reviews.container
  .row
    .col-sm-10.col-sm-offset-1
      = form_for [@video, Review.new] do |f| 
        %fieldset
          .form-group
            %label Rate this video
            = f.select :rating, options_for_video_reviews
          .form-group
            %label Write Review
            = f.text_area :content, rows: 6, class: "span6"
        %fieldset.form-group.actions.clearfix
          %input(type="submit" value="Submit" class="btn")
          = link_to "Cancel", @video 
      %header 
        %h3 User Reviews (#{@reviews.count})
      %ul
        - @reviews.each do |review|
          %article.review
            %li.row
              .col-sm-2
                %span Rating: #{review.rating} / 5
                %p 
                  by 
                  = link_to review.user.full_name, review.user
              .cols-sm-8
                %p= review.content 