config/routes.rb
Myflix::Application.routes.draw do
  root to:'pages#front'
  get 'home', to: 'videos#index'
  resources :videos, only: [:index, :show] do 
    collection do 
      post :search, to: 'videos#search'
    end 
    resources :reviews, only: [:create]
  end 

  namespace :admin do 
    resources :videos, only: [:new, :create]
  end 

  get "people", to: "relationships#index"
  resources :relationships, only: [:create, :destroy]

  resources :categories, only: [:index, :show]
  resources :queue_items, only: [:create, :destroy]

  post 'update_queue', to: 'queue_items#update_queue'
  get 'my_queue',   to: 'queue_items#index'

  get 'ui(/:action)', controller: 'ui'
  get 'register',  to: 'users#new'
  get 'register/:token', to: "users#new_with_invitation_token", as: "register_with_token"
  get 'sign_in',   to: 'sessions#new'
  get 'sign_out',  to: 'sessions#destroy'
  resources :users, only: [:create, :show]
  resources :sessions, only: [:create]

  get "forgot_password", to: "forgot_passwords#new"
  resources :forgot_passwords, only: [:create]
  get "forgot_password_confirmation", to: "forgot_passwords#confirm"
  resources :password_resets, only: [:show, :create]
  get "expired_token" , to: "pages#expired_token"

  resources :invitations, only: [:new, :create]

end
  

app/views/shared/_header.html.haml
%section#top-header.row
  %h1.col-md-2
    = link_to "MyFlix", root_path
  - if current_user 
    %ul.col-md-3
      %li= link_to "Videos", videos_path 
      %li= link_to "My Queue", my_queue_path
      %li= link_to "People", people_path 
    .col-md-5
      = form_tag search_videos_path, class: "span6 search-for" do 
        .form-group
          %input.form-control(name="search_term" type="text" placeholder="Search for videos here")
            %button.btn.btn-default(type="submit") Search
    #user_links.pull-right
      %ul
        %li.dropdown
          %a(href="#" id="dlabel" role="button" data-toggle="dropdown" class="dropdown-toggle" data-target="#")
            Welcome, #{current_user.full_name}
            %b.caret
          %ul.dropdown-menu(role="menu" aria-labelledby="dlabel")
            %li= link_to "Invite a Friend", new_invitation_path
            %li= link_to "Account", user_path(current_user)
            %li= link_to "Plan and Billing" 
            %li= link_to "Add New Video", new_admin_video_path if current_user.admin?
            %li= link_to "Sign Out", sign_out_path  

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  %div(class="alert alert-#{name}")
    %a.close(data-dismiss='alert') &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)